CLIENT_ENDPOINT_ID = "client"
SERVER_ENDPOINT_ID = "server"

NANOSECONDS_PER_MILLISECOND = 1_000_000
MILLISECONDS_PER_SECOND = 1_000

DEFAULT_OTEL_SERVICE_NAME = "server"

MODEL_ATTRIBUTE = "model"
NODE_ID_ATTRIBUTE = "node_id"
STAGE_ID_ATTRIBUTE = "stage_id"
DEVICE_ATTRIBUTE = "device"
LAYER_START_ATTRIBUTE = "layer_start"
LAYER_END_ATTRIBUTE = "layer_end"
PHASE_ATTRIBUTE = "phase"
SOURCE_NODE_ID_ATTRIBUTE = "source_node_id"
TARGET_NODE_ID_ATTRIBUTE = "target_node_id"
MESSAGE_TYPE_ATTRIBUTE = "message_type"
